### ISSUE TITLE
Difference in WER from just cleaned test set, without re-training

### ISSUE THREAD

**Issue by reuben** [dabinat/bad-cv-clips#2]
I was wondering if you have tested the DeepSpeech 0.5.1 checkpoint on the updated test set with bad sentences removed (without any re-training) to see how much impact just the bad test samples have in the WER.

**Comment by dabinat** [comment]
Without training:
WER before: 0.488338
WER after: 0.469518

With training:
WER before: 0.488426
WER after: 0.465491

So around a 2% reduction in WER for both (also a 2% reduction in CER and a 3% reduction in loss). 

Probably the most noticeable effect it has is on the report at the end. You no longer get crazy high losses like 400 or transcripts that are obviously wrong.

**Comment by dabinat** [comment]
Forgot to add, it removes 476 files from the validated test set.

**Comment by reuben** [comment]
Thanks!
